/**
 * @class AdministrativeService
 * @classdesc Represents a single administrative service request from a citizen or family.
 */
class AdministrativeService {
  /**
   * @param {object} data - The data to populate the entity.
   */
  constructor(data) {
    this.id = data.id;
    this.citizenId = data.citizenId;
    this.familyId = data.familyId || null; // Optional, for family-level requests
    this.requestType = data.requestType; // e.g., 'SURAT_PENGANTAR', 'SKTM'
    this.requestNumber = data.requestNumber || null; // Generated by service
    this.requestDate = data.requestDate; // Date the request was initiated
    this.submissionDate = data.submissionDate || null; // Date submitted to RT/RW
    this.requestStatus = data.requestStatus || 'DRAFT'; // e.g., 'DRAFT', 'SUBMITTED', 'RT_VERIFIED', 'RW_VERIFIED', 'KELURAHAN_PROCESSED', 'COMPLETED', 'REJECTED', 'CANCELLED'
    this.priority = data.priority || 'NORMAL'; // e.g., 'NORMAL', 'URGENT'
    this.reason = data.reason || null; // Citizen's reason for the request
    this.notes = data.notes || []; // Array of internal notes/comments
    this.attachments = data.attachments || []; // Array of attachment IDs/references

    // Verification/Processing details
    this.rt = data.rt; // RT of the requesting citizen/family
    this.rw = data.rw; // RW of the requesting citizen/family
    this.rtVerificationStatus = data.rtVerificationStatus || 'PENDING';
    this.rtVerifierId = data.rtVerifierId || null;
    this.rtVerificationDate = data.rtVerificationDate || null;
    this.rwVerificationStatus = data.rwVerificationStatus || 'PENDING';
    this.rwVerifierId = data.rwVerifierId || null;
    this.rwVerificationDate = data.rwVerificationDate || null;
    this.kelurahanProcessingStatus = data.kelurahanProcessingStatus || 'PENDING';
    this.kelurahanProcessorId = data.kelurahanProcessorId || null;
    this.kelurahanProcessingDate = data.kelurahanProcessingDate || null;

    this.completedAt = data.completedAt || null;
    this.completedBy = data.completedBy || null;
    this.cancelledAt = data.cancelledAt || null;
    this.cancelledBy = data.cancelledBy || null;

    this.createdAt = data.createdAt || new Date().toISOString();
    this.updatedAt = data.updatedAt || new Date().toISOString();
    this.createdBy = data.createdBy;
    this.updatedBy = data.updatedBy;
    this.deletedAt = data.deletedAt || null;
    this.deletedBy = data.deletedBy || null;
    this.version = data.version || 1;
  }

  /**
   * Returns a plain object representation of the entity for database operations.
   * @returns {object}
   */
  toObject() {
    return {
      id: this.id,
      citizenId: this.citizenId,
      familyId: this.familyId,
      requestType: this.requestType,
      requestNumber: this.requestNumber,
      requestDate: this.requestDate,
      submissionDate: this.submissionDate,
      requestStatus: this.requestStatus,
      priority: this.priority,
      reason: this.reason,
      notes: JSON.stringify(this.notes), // Store as JSON string
      attachments: JSON.stringify(this.attachments), // Store as JSON string
      rt: this.rt,
      rw: this.rw,
      rtVerificationStatus: this.rtVerificationStatus,
      rtVerifierId: this.rtVerifierId,
      rtVerificationDate: this.rtVerificationDate,
      rwVerificationStatus: this.rwVerificationStatus,
      rwVerifierId: this.rwVerifierId,
      rwVerificationDate: this.rwVerificationDate,
      kelurahanProcessingStatus: this.kelurahanProcessingStatus,
      kelurahanProcessorId: this.kelurahanProcessorId,
      kelurahanProcessingDate: this.kelurahanProcessingDate,
      completedAt: this.completedAt,
      completedBy: this.completedBy,
      cancelledAt: this.cancelledAt,
      cancelledBy: this.cancelledBy,
      createdAt: this.createdAt,
      updatedAt: this.updatedAt,
      createdBy: this.createdBy,
      updatedBy: this.updatedBy,
      deletedAt: this.deletedAt,
      deletedBy: this.deletedBy,
      version: this.version,
    };
  }

  /**
   * Creates an entity instance from a database record.
   * @param {object} record - The database record.
   * @returns {AdministrativeService|null}
   */
  static fromObject(record) {
    if (!record) {
      return null;
    }
    const data = { ...record };
    try {
      data.notes = typeof record.notes === 'string' ? JSON.parse(record.notes) : (record.notes || []);
    } catch (e) {
      data.notes = [];
    }
    try {
      data.attachments = typeof record.attachments === 'string' ? JSON.parse(record.attachments) : (record.attachments || []);
    } catch (e) {
      data.attachments = [];
    }
    return new AdministrativeService(data);
  }
}