#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

usage() {
  cat <<'EOF'
WK Generator Entry Point

Usage:
  generator.sh <module-name> [options]

Examples:
  generator.sh Citizen
  generator.sh Family
EOF
}

if [[ $# -lt 1 ]]; then
  usage
  exit 1
fi

MODULE_NAME="$1"
shift

cat <<EOF
Generating module scaffold for: $MODULE_NAME
Root: $ROOT_DIR
EOF

mkdir -p "$ROOT_DIR/packages/$MODULE_NAME"
mkdir -p "$ROOT_DIR/packages/$MODULE_NAME/controllers"
mkdir -p "$ROOT_DIR/packages/$MODULE_NAME/services"
mkdir -p "$ROOT_DIR/packages/$MODULE_NAME/tests"

cat > "$ROOT_DIR/packages/$MODULE_NAME/README.md" <<EOT
# $MODULE_NAME Module

Generated by the Native WK CLI generator entrypoint.
EOT
